# Chapter 2 - Machine Learning using Regression Models.

## Project: Car Price Predicator.

In [2]:
# Importing python packages

# Data manipulation packages
import numpy as np
import pandas as pd

# Data Visualization Pactages
import matplotlib.pyplot as plt
import seaborn as sns

# Visualizer code
%matplotlib inline

C:\Users\User1\anaconda3\envs\ml-zoomcamp\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.1
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

## Data Gathering.

In [9]:
# Loading dataset.
car = pd.read_csv('data/data.csv')

# Viewing dataset
car.head()

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500

## Data Assessment.

In [13]:
# Data Summary 
car.sample(10)

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
10264,Chevrolet,Tahoe,2016,flex-fuel (unleaded/E85),355.0,8.0,AUTOMATIC,four wheel drive,4.0,Flex Fuel,Large,4dr SUV,22,16,1385,50000
1139,GMC,Acadia,2015,regular unleaded,281.0,6.0,AUTOMATIC,front wheel drive,4.0,Crossover,Midsize,4dr SUV,24,17,549,33975
4366,Ford,Explorer Sport Trac,2009,regular unleaded,210.0,6.0,AUTOMATIC,rear wheel drive,4.0,Crossover,Compact,Crew Cab Pickup,20,14,5657,25985
795,Volvo,850,1997,regular unleaded,190.0,5.0,AUTOMATIC,front wheel drive,4.0,"Luxury,Performance",Midsize,Wagon,24,18,870,2000
8423,Acura,RDX,2016,premium unleaded (recommended),279.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Luxury",Midsize,4dr SUV,28,19,204,36870
233,Chrysler,300M,2002,premium unleaded (required),250.0,6.0,AUTOMATIC,front wheel drive,4.0,Performance,Large,Sedan,24,16,1013,32065
357,Nissan,370Z,2017,premium unleaded (required),332.0,6.0,AUTOMATIC,rear wheel drive,2.0,High-Performance,Compact,Coupe,26,19,2009,31290
2569,Honda,Civic,2016,regular unleaded,174.0,4.0,AUTOMATIC,front wheel drive,2.0,NaN,Compact,Coupe,41,31,2202,26125
5160,Infiniti,G37,2008,premium unleaded (required),330.0,6.0,AUTOMATIC,rear wheel drive,2.0,"Luxury,Performance",Midsize,Coupe,24,18,190,35650
11846,GMC,Yukon XL,2015,flex-fuel (unleaded/E85),355.0,8.0,AUTOMATIC,rear wheel drive,4.0,Flex Fuel,Large,4dr SUV,23,16,549,58925

In [10]:
# Viewing the data shape. 
print(f"There are {car.shape[0]} rows and {car.shape[1]} columns in the car dataset")

There are 11914 rows and 16 columns in the car dataset

In [11]:
# Columns in the dataset
car.columns

Index(['Make', 'Model', 'Year', 'Engine Fuel Type', 'Engine HP',
       'Engine Cylinders', 'Transmission Type', 'Driven_Wheels',
       'Number of Doors', 'Market Category', 'Vehicle Size', 'Vehicle Style',
       'highway MPG', 'city mpg', 'Popularity', 'MSRP'],
      dtype='object')

In [12]:
# Data structure 
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Make               11914 non-null  object
 1   Model              11914 non-null  object
 2   Year               11914 non-null  int64
 3   Engine Fuel Type   11911 non-null  object
 4   Engine HP          11845 non-null  float64
 5   Engine Cylinders   11884 non-null  float64
 6   Transmission Type  11914 non-null  object
 7   Driven_Wheels      11914 non-null  object
 8   Number of Doors    11908 non-null  float64
 9   Market Category    8172 non-null   object
 10  Vehicle Size       11914 non-null  object
 11  Vehicle Style      11914 non-null  object
 12  highway MPG        11914 non-null  int64
 13  city mpg           11914 non-null  int64
 14  Popularity         11914 non-null  int64
 15  MSRP               11914 non-null  int64
dtypes: float64(3), int64(5), object(8)
memory usage: 1.5+ MB

In [15]:
# checking unique values from each data set
car[car.dtype()== "float"]

AttributeError: 'DataFrame' object has no attribute 'dtype'

### Data Cleaning Observation: 
- Column names needs to be renamed and replace all space with _
- Converting all object to lower case and replacing spaces with _ 
-